/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2016-06-29T14:47:28.233-06:00
  3.8.2.6
  
  Standalone prediction code with sample test data for KMeansModel named KMeans_model_R_1467231909822_2

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://127.0.0.1:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://127.0.0.1:54321/3/Models.java/KMeans_model_R_1467231909822_2 > KMeans_model_R_1467231909822_2.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m KMeans_model_R_1467231909822_2.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
package hello;
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="KMeans_model_R_1467231909822_2", algorithm="kmeans")
public class KMeans_model_R_1467231909822_2 extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Clustering; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_KMeans_model_R_1467231909822_2.VALUES;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* sepal_length */ null,
    /* sepal_width */ null,
    /* petal_length */ null,
    /* petal_width */ null
  };

  public KMeans_model_R_1467231909822_2() { super(NAMES,DOMAINS); }
  public String getUUID() { return Long.toString(5345698953211792916L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    preds[0] = KMeans_closest(KMeans_model_R_1467231909822_2_CENTERS.VALUES, data, DOMAINS, KMeans_model_R_1467231909822_2_MEANS.VALUES, KMeans_model_R_1467231909822_2_MULTS.VALUES);
    return preds;
  }
}
// The class representing training column names
class NamesHolder_KMeans_model_R_1467231909822_2 implements java.io.Serializable {
  public static final String[] VALUES = new String[4];
  static {
    NamesHolder_KMeans_model_R_1467231909822_2_0.fill(VALUES);
  }
  static final class NamesHolder_KMeans_model_R_1467231909822_2_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "sepal_length";
      sa[1] = "sepal_width";
      sa[2] = "petal_length";
      sa[3] = "petal_width";
    }
  }
}
// Column means of training data
class KMeans_model_R_1467231909822_2_MEANS implements java.io.Serializable {
  public static final double[] VALUES = new double[4];
  static {
    KMeans_model_R_1467231909822_2_MEANS_0.fill(VALUES);
  }
  static final class KMeans_model_R_1467231909822_2_MEANS_0 implements java.io.Serializable {
    static final void fill(double[] sa) {
      sa[0] = 5.843333333333334;
      sa[1] = 3.0539999999999994;
      sa[2] = 3.758666666666667;
      sa[3] = 1.1986666666666668;
    }
  }
}
// Reciprocal of column standard deviations of training data
class KMeans_model_R_1467231909822_2_MULTS implements java.io.Serializable {
  public static final double[] VALUES = new double[4];
  static {
    KMeans_model_R_1467231909822_2_MULTS_0.fill(VALUES);
  }
  static final class KMeans_model_R_1467231909822_2_MULTS_0 implements java.io.Serializable {
    static final void fill(double[] sa) {
      sa[0] = 1.2076330213409388;
      sa[1] = 2.306303320397388;
      sa[2] = 0.5667583466456683;
      sa[3] = 1.3103399393571;
    }
  }
}
// Normalized cluster centers[K][features]
class KMeans_model_R_1467231909822_2_CENTERS implements java.io.Serializable {
  public static final double[][] VALUES = new double[3][];
  static {
    KMeans_model_R_1467231909822_2_CENTERS_0.fill(VALUES);
  }
  static class KMeans_model_R_1467231909822_2_CENTERS_0_0 implements java.io.Serializable {
    public static final double[] VALUES = new double[4];
    static {
      KMeans_model_R_1467231909822_2_CENTERS_0_0_0.fill(VALUES);
    }
    static final class KMeans_model_R_1467231909822_2_CENTERS_0_0_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = -0.05005221138765279;
        sa[1] = -0.8773525952047551;
        sa[2] = 0.34637133371228207;
        sa[3] = 0.2811214843481093;
      }
    }
}
  static class KMeans_model_R_1467231909822_2_CENTERS_0_1 implements java.io.Serializable {
    public static final double[] VALUES = new double[4];
    static {
      KMeans_model_R_1467231909822_2_CENTERS_0_1_0.fill(VALUES);
    }
    static final class KMeans_model_R_1467231909822_2_CENTERS_0_1_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = -1.0111913832028134;
        sa[1] = 0.8394944086246511;
        sa[2] = -1.300521486102928;
        sa[3] = -1.250937862106244;
      }
    }
}
  static class KMeans_model_R_1467231909822_2_CENTERS_0_2 implements java.io.Serializable {
    public static final double[] VALUES = new double[4];
    static {
      KMeans_model_R_1467231909822_2_CENTERS_0_2_0.fill(VALUES);
    }
    static final class KMeans_model_R_1467231909822_2_CENTERS_0_2_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = 1.132177369440132;
        sa[1] = 0.09627589605573954;
        sa[2] = 0.9929445450722417;
        sa[3] = 1.013775626273669;
      }
    }
}
  static final class KMeans_model_R_1467231909822_2_CENTERS_0 implements java.io.Serializable {
    static final void fill(double[][] sa) {
      sa[0] = KMeans_model_R_1467231909822_2_CENTERS_0_0.VALUES;
      sa[1] = KMeans_model_R_1467231909822_2_CENTERS_0_1.VALUES;
      sa[2] = KMeans_model_R_1467231909822_2_CENTERS_0_2.VALUES;
    }
  }
}


